server:
    port: 8888

spring:
    activemq:
        broker-url: tcp://192.168.10.4:61616
        user: admin
        password: admin
    jms:
        pub-sub-domain: false #默认false false = Queue  true = Topic

#自己定义队列名称
myqueue: boot-activemq-queue